# Generated by Django 2.2.4 on 2019-09-02 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20190902_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(verbose_name='Maximum Capacity'),
        ),
        migrations.AlterField(
            model_name='group',
            name='weekly_amount',
            field=models.IntegerField(verbose_name='Periodic Amount'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount payed')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ManyToManyField(related_name='group', to='group.Group')),
                ('user', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
