# Generated by Django 2.2.4 on 2019-09-02 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20190902_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ManyToManyField(editable=False, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
