# Generated by Django 2.2.4 on 2019-09-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20190902_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='payer',
        ),
    ]
